import { type Profile,type Source,type Bridge,type Recommendation,type Week,type Draft,tracks,profileSchema,understandSchema,validateBridge,validateWeek,validateDraft } from './contracts';
export const sampleStory="I'm Omar. We're moving from London to Abu Dhabi for my fintech job at ADGM. My wife Sara is a graphic designer with six years of experience and wants to explore work here. We have a four-year-old daughter, Lina, and we're planning to live on Al Reem Island. Sara loves photography, Pilates, art and coffee, but she's worried about not knowing anyone here. We want our first week to feel manageable and to help everyone find their own routine.";
export const sampleProfile:Profile=profileSchema.parse({id:'family-demo',originCity:'London',destinationCity:'Abu Dhabi',preferredArea:'Al Reem Island',employerContext:'Fintech role at ADGM',arrivalDate:null,people:[{id:'omar',name:'Omar',role:'employee',age:null,profession:'Fintech employee',experienceYears:null,goals:['Settle into a routine','Support the family'],interests:[],concerns:[]},{id:'sara',name:'Sara',role:'partner',age:null,profession:'Graphic designer',experienceYears:6,goals:['Explore design work','Meet people and build a routine'],interests:['Photography','Pilates','Art','Coffee'],concerns:["I don’t know anyone here."]},{id:'lina',name:'Lina',role:'child',age:4,profession:null,experienceYears:null,goals:['Build an age-appropriate family routine'],interests:[],concerns:[]}],constraints:{budgetNote:null,transport:null,childcare:null,availability:null},facts:[{fieldPath:'originCity',evidence:'user_stated',text:'Moving from London'},{fieldPath:'people.sara.profession',evidence:'user_stated',text:'Graphic designer with six years of experience'},{fieldPath:'preferredArea',evidence:'user_stated',text:'Planning to live on Al Reem Island'}],unknowns:['Arrival date','Budget','Transport','Childcare','Workday availability','Work authorization','School or nursery preferences','Languages'],assumptions:['Tasks stay flexible around work and childcare.']});
export function sameSample(p:Profile){return JSON.stringify({...p,facts:[],assumptions:[]})===JSON.stringify({...sampleProfile,facts:[],assumptions:[]});}
export const sampleUnderstanding=understandSchema.parse({profile:sampleProfile,reviewSummary:'Sara wants to explore design work and find her people. Omar is starting a fintech role, while the family wants a gentle routine for four-year-old Lina.',clarifyingQuestions:[{fieldPath:'arrivalDate',question:'When does your first week begin?'},{fieldPath:'constraints.childcare',question:'What childcare support will you have?'},{fieldPath:'constraints.availability',question:'How much time feels manageable?'}]});
const goals={career:'Make room for your next chapter.',community:'Begin with one easy connection.',family:'Find a rhythm that works together.',personal:'Keep a little time that feels like you.'};
export function buildSample(sources:Source[]=[]):Bridge{
 const r=(id:string,title:string,track:Recommendation['track'],personIds:string[],rationale:string,nextStep:string,effortMinutes:number,actionIntent:Recommendation['actionIntent']='none'):Recommendation=>({id,title,track,personIds,kind:'self_directed',catalogId:null,sourceIds:[],rationale,nextStep,effortMinutes,effortLabel:'planning_estimate',requiresChecking:[],actionIntent});
 const recs:Recommendation[]=[
 r('career-goals','Write your three career goals','career',['sara'],'Six years in graphic design is a starting point. Sara can decide what she wants her next chapter to look like.','Write three goals and one type of design work you want to explore.',20),
 r('portfolio','Choose three portfolio projects','career',['sara'],'Sara can draw on six years of design experience without rushing into an application.','Choose three existing projects and write a short explanation of each.',30,'portfolio_checklist'),
 r('intro',"Prepare Sara’s first design-community introduction",'community',['sara'],'Sara wants to explore work and is worried about not knowing anyone. One low-pressure introduction connects both goals.','Prepare an introduction, then decide where you feel comfortable sharing it.',20,'draft_introduction'),
 r('photography','Find a photography contact pathway','community',['sara'],'Photography gives Sara a shared interest to begin a conversation.','Look for a public photography or creative-community contact page; verify how newcomers can join.',20),
 r('routine','Agree one family routine to preserve','family',['omar','sara','lina'],'A familiar routine can be a useful anchor for four-year-old Lina during the move.','Omar and Sara choose one familiar activity to keep with Lina.',15),
 r('time','Find a workable family time window','family',['omar','sara'],'Omar is starting a fintech role and availability is still unknown. Agree a realistic window before arranging anything.','Talk about work and childcare; choose one flexible family time window.',10),
 r('outing','Plan a caregiver-led activity for Lina','family',['omar','sara','lina'],'Lina is four. A small activity with a caregiver keeps the first week manageable.','Choose a low-effort family activity. Check age suitability, transport and availability before visiting.',20),
 r('art','Explore an arts and culture resource','personal',['sara'],'Art is one of Sara’s interests. Browsing first leaves room to choose without committing to a schedule.','Identify an official arts resource and check its current visitor information.',20),
 r('pilates','Shortlist Pilates options to verify','personal',['sara'],'Sara enjoys Pilates. A shortlist helps preserve personal time without inventing a class or slot.','Find two options; check location, pricing and availability yourself.',20),
 r('review','Reflect and choose one next step','personal',['omar','sara'],'The family wants a manageable first week, with room for each person’s routine.','Talk about what felt useful and choose one small step for next week.',15)];
 const official=sources.find(s=>s.kind==='official');if(official)recs[6]={...recs[6],title:'Review official education information',kind:'catalog_resource',catalogId:official.id,sourceIds:[official.id],nextStep:'Open ADEK’s education information. Note questions about Lina’s school or nursery options; check directly before making decisions.',requiresChecking:['Age suitability and admissions','Current requirements']};
 const art=sources.find(s=>s.id==='cultural-foundation');if(art)recs[7]={...recs[7],kind:'catalog_resource',catalogId:art.id,sourceIds:[art.id],nextStep:'Open the Cultural Foundation visitor resource; verify current information before planning a visit.',requiresChecking:['Current opening and admission information','Transport']};
 for(const s of sources.filter(s=>s.kind==='job').slice(0,2))recs.push({...r('job-'+s.id,'Review: '+s.title.slice(0,80),'career',['sara'],'Sara wants to explore design work. This Abu Dhabi design-related lead needs a careful skills review; graphic design experience alone does not establish a fit.', 'Read the original role and compare requirements with your experience. Work eligibility and acceptance of applications remain unverified.',20),kind:'catalog_resource',catalogId:s.id,sourceIds:[s.id],requiresChecking:['Role fit','Work eligibility','Whether applications remain open']});
 return validateBridge({id:'bridge-demo',profileId:sampleProfile.id,headline:'A life for everyone, starting with Sara.',summary:'A few useful steps across work, people, family and time for yourself.',tracks:tracks.map(id=>({id,goal:goals[id],recommendationIds:recs.filter(r=>r.track===id).map(r=>r.id)})),recommendations:recs,featuredRecommendationId:'intro',assumptions:['Suggested preparation, not appointments.','Work authorization, childcare and availability remain unknown.']},sampleProfile,sources);
}
export function buildWeek(b:Bridge,lighter=false,saved:string[]=[],completed:string[]=[]):Week{
 const rows:[number,string,string][]=[[1,'career-goals',"Write Sara’s three career goals"],[1,'routine','Agree one family routine to preserve'],[2,'intro',"Prepare Sara’s community introduction"],[3,'portfolio','Choose three portfolio projects to explain'],[4,'art','Explore an arts and culture resource page'],[4,'time','Ask Omar about a workable family time window'],[5,'photography','Find a public photography contact pathway'],[6,'outing',b.recommendations.find(r=>r.id==='outing')!.title],[7,'pilates','Make a shortlist of Pilates options to verify'],[7,'review','Review the week and choose one next step']];
 let tasks=rows.map(([dayIndex,key,title])=>{const r=b.recommendations.find(r=>r.id===key)!;return {id:'task-'+key,dayIndex,recommendationId:r.id,title,personIds:r.personIds,track:r.track,effortMinutes:r.effortMinutes,timeWindow:'flexible' as const,rationale:r.rationale,requiresChecking:r.requiresChecking};});
 if(lighter){const next:typeof tasks=[];for(let day=1;day<=7;day++){const candidates=tasks.filter(t=>t.dayIndex===day);candidates.sort((a,b)=>Number(completed.includes(b.id))-Number(completed.includes(a.id))||Number(saved.includes(b.recommendationId))-Number(saved.includes(a.recommendationId)));next.push(...candidates.slice(0,1));}const omittedCompleted=tasks.filter(t=>completed.includes(t.id)&&!next.some(n=>n.id===t.id));for(const t of omittedCompleted){const free=Array.from({length:7},(_,i)=>i+1).find(d=>!next.some(n=>n.dayIndex===d));if(free)next.push({...t,dayIndex:free});else return buildWeek(b,false,saved,completed);}tasks=next;}
 return validateWeek({id:'week-demo',bridgeId:b.id,startDate:null,timezone:'Asia/Dubai',tasks,assumptions:['Suggested sequence; adjust around work and childcare.','Estimated effort describes preparation, not travel or venue time.']},b,lighter?1:2);
}
export function sampleDraft(r:Recommendation,tone:'warm'|'concise'='warm',context=''):Draft{
 const warm="Hi, I’m Sara, a graphic designer with six years of experience, preparing to move from London to Abu Dhabi. I’m hoping to meet other designers and learn more about the local creative community as I find my feet in a new city. I enjoy photography and art, and I’d love to hear about approachable ways to get involved. I’m interested in conversations about design, sharing ideas and getting to know people with similar interests. If you welcome newcomers, could you point me toward an upcoming public gathering or a suitable introduction? There’s no rush—I’d appreciate any guidance on where to begin. Thank you for your time, Sara.";
 const concise="Hi, I’m Sara, a graphic designer with six years of experience. I’m preparing to move from London to Abu Dhabi and would like to connect with the local creative community. My interests include photography and art, and I’m hoping to learn how newcomers can get involved. Could you suggest a public gathering, a community contact pathway or someone who could offer an introduction? I’d appreciate a simple starting point that I can explore around my family’s first-week routine. I’m looking forward to learning more about design in Abu Dhabi and meeting people who share these interests. Thank you for any guidance you can share. Best, Sara.";
 return validateDraft({id:'draft-demo',recommendationId:r.id,intent:r.actionIntent==='portfolio_checklist'?'portfolio_checklist':'draft_introduction',title:r.actionIntent==='portfolio_checklist'?'Prepare your portfolio':"Prepare Sara’s first connection",channel:'Community contact form or message',recipientLabel:null,recipientAddress:null,subject:'A design-community introduction',body:(r.actionIntent==='portfolio_checklist'?'Project 1: What did I design, and what was my role?\n\nProject 2: What did I design, and what was my role?\n\nProject 3: What did I design, and what was my role?\n\nBefore sharing: confirm permission and add a portfolio link only if you choose.':tone==='warm'?warm:concise)+(context.trim()?'\n\n'+context.trim():''),checklist:r.actionIntent==='portfolio_checklist'?['Choose three existing projects.','Explain your role in each.','Check that you can share the work.','Add a portfolio link yourself, if you want.']:[],sourceIds:r.sourceIds,reviewNotes:['Choose and verify the recipient yourself.','Add a portfolio link only if you want to share it.','Your added context is appended verbatim; this sample is not AI-personalized.'],executionStatus:'draft_only'},r);
}
