import {z} from 'zod';
import {type Profile,type Bridge,type Source,validateBridge,type Recommendation,tracks,type Draft,type Week,validateWeek} from './contracts';
export const lifestyleSchema=z.object({cuisines:z.array(z.string().max(60)).max(8),diets:z.array(z.string().max(60)).max(8),dislikes:z.array(z.string().max(60)).max(8),vibes:z.array(z.string().max(60)).max(8),budget:z.enum(['Explore all','Everyday','Treat yourself']),socialLinks:z.record(z.string().max(100),z.array(z.string().url().max(300)).max(3))}).strict();
export type Lifestyle=z.infer<typeof lifestyleSchema>;
export const defaultLifestyle:Lifestyle={cuisines:['Emirati','Japanese','Coffee'],diets:[],dislikes:[],vibes:['Waterfront','Arts & culture','Family-friendly'],budget:'Explore all',socialLinks:{}};
export const blankLifestyle:Lifestyle={cuisines:[],diets:[],dislikes:[],vibes:[],budget:'Explore all',socialLinks:{}};
export const interests=['Photography','Art','Coffee','Pilates','Running','Cycling','Gaming','Reading'];
export const goalOptions=['Find work','Meet people','Explore the city','Build a routine','Find a home'];
export const cuisineOptions=['Emirati','Indian','Japanese','Italian','Lebanese','Korean','Coffee','Seafood'];
export const dietOptions=['Vegetarian','Vegan','Halal','Gluten-free'];
export const vibeOptions=['Waterfront','Arts & culture','Family-friendly','City energy','Quiet & green','Entertainment'];
export const areas=[
 {id:'saadiyat',name:'Saadiyat Island',tags:['Waterfront','Arts & culture','Quiet & green'],note:'Beach days and a cultural district.',source:'https://visitabudhabi.ae/en/where-to-go/islands/saadiyat-island',query:'Saadiyat Island Abu Dhabi'},
 {id:'yas',name:'Yas Island',tags:['Entertainment','Family-friendly','Waterfront'],note:'Leisure attractions and island living.',source:'https://www.yasisland.com/',query:'Yas Island Abu Dhabi'},
 {id:'reem',name:'Al Reem Island',tags:['City energy','Waterfront','Family-friendly'],note:'Urban island with towers and parks.',source:'https://visitabudhabi.ae/en/where-to-go/islands/al-reem-island',query:'Al Reem Island Abu Dhabi'},
 {id:'corniche',name:'Corniche',tags:['Waterfront','City energy','Family-friendly'],note:'A city waterfront with a public promenade.',source:'https://visitabudhabi.ae/en/where-to-go/beaches/corniche-beach',query:'Corniche Abu Dhabi'}
];
export function rankedAreas(p:Lifestyle){return areas.map(a=>({...a,matches:a.tags.filter(t=>p.vibes.includes(t))})).sort((a,b)=>b.matches.length-a.matches.length);}
export const mapSearch=(query:string)=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(query);
export function blankProfile():Profile{return {id:'family-'+crypto.randomUUID(),originCity:null,destinationCity:'Abu Dhabi',preferredArea:null,employerContext:null,arrivalDate:null,people:[{id:'person-'+crypto.randomUUID(),name:'',role:'employee',age:null,profession:null,experienceYears:null,goals:[],interests:[],concerns:[]}],constraints:{budgetNote:null,transport:null,childcare:null,availability:null},facts:[],unknowns:[],assumptions:[]};}
export function choiceBridge(profile:Profile,p: Lifestyle,sources:Source[]):Bridge{
 const adults=profile.people.filter(x=>x.role!=='child'),people=adults.length?adults:profile.people;const partner=people.find(x=>x.role==='partner'),lead=people.find(x=>x.goals.includes('Find work'))||partner||people[0],social=people.find(x=>x.goals.includes('Meet people'))||partner||people[0],family=profile.people.map(x=>x.id),area=rankedAreas(p)[0],children=profile.people.filter(x=>x.role==='child');
 const rs:Recommendation[]=[];const add=(title:string,track:Recommendation['track'],personIds:string[],nextStep:string,rationale:string,actionIntent:Recommendation['actionIntent']='none',effortMinutes=15)=>rs.push({id:'choice-'+rs.length,title,track,personIds,kind:'self_directed',catalogId:null,sourceIds:[],nextStep,rationale,effortMinutes,effortLabel:'planning_estimate',requiresChecking:[],actionIntent});
 add('Map '+lead.name+'’s next career move','career',[lead.id],'List two target roles, your preferred hours and three strengths. Search five Abu Dhabi employers and save two relevant vacancies. Check work eligibility on MOHRE before applying.','A move should open doors for the partner, too.','draft_introduction',25);
 const interest=social.interests[0]||'a shared interest';add('Find '+social.name+'’s '+interest.toLowerCase()+' circle','community',people.map(x=>x.id),'Search public '+interest.toLowerCase()+' groups in Discover. Shortlist two beginner-friendly gatherings. Ask the organiser about the next date, price and whether newcomers can attend.','Friendship starts with something you already love.','draft_introduction',20);
 add(children.length?'Give the children a familiar first week':'Bring a piece of home with you','family',family,children.length?'Choose a familiar bedtime, meal and comfort item with the children. Schedule a call with one friend back home. Let each child pick one small weekend adventure.':'Choose one meal, one familiar routine and a weekly call with someone back home. Put them in your shared calendar.','Moving is easier when something still feels familiar.','none',15);
 add('Build a CV that opens a conversation','career',[lead.id],'Update your location and contact details. Select three achievements with clear results. Check every portfolio link. Prepare a 60-second introduction for a recruiter or community contact.',lead.profession?'Turn your '+lead.profession+' experience into a clear next step.':'Make your experience easy for someone new to understand.','portfolio_checklist',30);
 add('Compare homes in '+area.name,'family',family,'Explore '+area.name+'. Compare work travel, school routes and everyday shops with a second area. Write down your maximum monthly budget and three non-negotiables before contacting an agent.','Start with '+area.name+': '+(area.matches.join(', ')||'one area to compare')+'.','none',30);
 add(children.length?'Prepare school and activity questions':'Make room for each other','family',family,children.length?'Create a school folder: passport, previous reports and vaccination records. Use ADEK to check age and admissions requirements. Ask two schools about places, fees, transport and settling-in support.':'Each adult chooses one personal goal and one shared activity. Agree who handles each moving task, with a short Sunday check-in.','Give every person a voice in the move.','none',25);
 add('Share a first favourite meal','personal',people.map(x=>x.id),'Search '+(p.cuisines[0]||'your favourite cuisine')+' in Discover. Compare three places by distance, menu and dietary needs. Choose one relaxed first outing and confirm opening hours.','A familiar flavour can make a new city feel closer.','none',15);
 add('Make one introduction, together','community',people.map(x=>x.id),'Draft a three-sentence hello: who you are, what you enjoy and the kind of connection you hope to make. Choose one public community contact, review the draft and send it yourself.','An invitation is easier when you have a starting point.','draft_introduction',15);
 add('Protect time beyond the new job','personal',people.map(x=>x.id),'Agree two 30-minute windows this week for the partner’s career or social plans. Choose who covers childcare and transport. Save those windows in your shared calendar.','The employee’s new job is one part of the family’s new life.','none',15);
 for(const src of sources.filter(x=>x.kind==='official').slice(0,1))rs.push({id:'choice-source-'+src.id,title:src.title.slice(0,100),track:src.track,personIds:family,kind:'catalog_resource',catalogId:src.id,sourceIds:[src.id],nextStep:'Check the original source before making arrangements.',rationale:'Official information for your household.',effortMinutes:15,effortLabel:'planning_estimate',requiresChecking:['Suitability and current requirements'],actionIntent:'none'});
 return validateBridge({id:'bridge-'+crypto.randomUUID(),profileId:profile.id,headline:'A new beginning for every person.',summary:'Careers, friendships and family routines, planned together.',tracks:tracks.map(id=>({id,goal:id,recommendationIds:rs.filter(r=>r.track===id).map(r=>r.id)})),recommendations:rs,featuredRecommendationId:rs[2].id,assumptions:['Suggested preparation steps; no bookings or messages are sent.']},profile,sources);
}
export function choiceDraft(r:Recommendation,profile:Profile,tone:'warm'|'concise',context:string):Draft{const person=profile.people.find(p=>r.personIds.includes(p.id)&&p.role!=='child')||profile.people[0];return {id:'draft-'+crypto.randomUUID(),recommendationId:r.id,intent:r.actionIntent==='portfolio_checklist'?'portfolio_checklist':'draft_introduction',title:r.actionIntent==='portfolio_checklist'?'Your preparation checklist':'A first hello',channel:'Copy and share with a contact you choose',recipientLabel:null,recipientAddress:null,subject:r.actionIntent==='portfolio_checklist'?null:'Hello from '+(person.name||'a new neighbour'),body:r.actionIntent==='portfolio_checklist'?'A few things to prepare before you reach out.':(tone==='warm'?'Hi there!':'Hello,')+' I’m '+(person.name||'a new neighbour')+(person.profession?', a '+person.profession:'')+'. I’m getting settled in Abu Dhabi and would love to connect with people who enjoy '+(person.interests.slice(0,3).join(', ')||'similar interests')+'. '+(context.trim()?context.trim()+' ':'')+'Do you have a public gathering or beginner-friendly activity you would recommend? Thank you!',checklist:r.actionIntent==='portfolio_checklist'?['Pick three relevant examples','Check that links open correctly','Write a short introduction','Choose who you want to contact']:['Choose the recipient','Review your details','Copy when ready'],sourceIds:r.sourceIds,reviewNotes:['Template built from your choices. Edit before sharing.'],executionStatus:'draft_only'};}

export function choiceWeek(b:Bridge):Week {return validateWeek({id:'week-'+crypto.randomUUID(),bridgeId:b.id,startDate:null,timezone:'Asia/Dubai',tasks:b.recommendations.map((r,i)=>({id:'task-'+crypto.randomUUID(),dayIndex:i<7?i+1:i-6,recommendationId:r.id,title:r.title,personIds:r.personIds,track:r.track,effortMinutes:r.effortMinutes,timeWindow:'flexible',rationale:r.rationale,requiresChecking:r.requiresChecking})),assumptions:['Suggested preparation sequence, not booked appointments.']},b);}
