import {z} from 'zod';
import {type Profile,type Bridge,type Source,validateBridge,type Recommendation,tracks,type Draft,type Week,validateWeek} from './contracts';
export const lifestyleSchema=z.object({cuisines:z.array(z.string().max(60)).max(8),diets:z.array(z.string().max(60)).max(8),dislikes:z.array(z.string().max(60)).max(8),vibes:z.array(z.string().max(60)).max(8),budget:z.enum(['Explore all','Everyday','Treat yourself']),socialLinks:z.record(z.string().max(100),z.array(z.string().url().max(300)).max(3))}).strict();
export type Lifestyle=z.infer<typeof lifestyleSchema>;
export const defaultLifestyle:Lifestyle={cuisines:['Emirati','Japanese','Coffee'],diets:[],dislikes:[],vibes:['Waterfront','Arts & culture','Family-friendly'],budget:'Explore all',socialLinks:{}};
export const blankLifestyle:Lifestyle={cuisines:[],diets:[],dislikes:[],vibes:[],budget:'Explore all',socialLinks:{}};
export const interests=['Photography','Art','Coffee','Pilates','Running','Cycling','Gaming','Reading'];
export const goalOptions=['Find work','Meet people','Explore the city','Build a routine','Find a home'];
export const cuisineOptions=['Emirati','Indian','Japanese','Italian','Lebanese','Korean','Coffee','Seafood'];
export const dietOptions=['Vegetarian','Vegan','Halal','Gluten-free'];
export const vibeOptions=['Waterfront','Arts & culture','Family-friendly','City energy','Quiet & green','Entertainment'];
export const areas=[
 {id:'saadiyat',name:'Saadiyat Island',tags:['Waterfront','Arts & culture','Quiet & green'],note:'Beach days and a cultural district.',source:'https://visitabudhabi.ae/en/where-to-go/islands/saadiyat-island',query:'Saadiyat Island Abu Dhabi'},
 {id:'yas',name:'Yas Island',tags:['Entertainment','Family-friendly','Waterfront'],note:'Leisure attractions and island living.',source:'https://www.yasisland.com/',query:'Yas Island Abu Dhabi'},
 {id:'reem',name:'Al Reem Island',tags:['City energy','Waterfront','Family-friendly'],note:'Urban island with towers and parks.',source:'https://visitabudhabi.ae/en/where-to-go/islands/al-reem-island',query:'Al Reem Island Abu Dhabi'},
 {id:'corniche',name:'Corniche',tags:['Waterfront','City energy','Family-friendly'],note:'A city waterfront with a public promenade.',source:'https://visitabudhabi.ae/en/where-to-go/beaches/corniche-beach',query:'Corniche Abu Dhabi'}
];
export function rankedAreas(p:Lifestyle){return areas.map(a=>({...a,matches:a.tags.filter(t=>p.vibes.includes(t))})).sort((a,b)=>b.matches.length-a.matches.length);}
export const mapSearch=(query:string)=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(query);
export function blankProfile():Profile{return {id:'family-'+crypto.randomUUID(),originCity:null,destinationCity:'Abu Dhabi',preferredArea:null,employerContext:null,arrivalDate:null,people:[{id:'person-'+crypto.randomUUID(),name:'',role:'employee',age:null,profession:null,experienceYears:null,goals:[],interests:[],concerns:[]}],constraints:{budgetNote:null,transport:null,childcare:null,availability:null},facts:[],unknowns:[],assumptions:[]};}
export function choiceBridge(profile:Profile,p: Lifestyle,sources:Source[]):Bridge{
 const adults=profile.people.filter(x=>x.role!=='child'),people=adults.length?adults:profile.people;const lead=people.find(x=>x.goals.includes('Find work'))||people[0],social=people.find(x=>x.goals.includes('Meet people'))||people[0],family=profile.people.map(x=>x.id),area=rankedAreas(p)[0];
 const rs:Recommendation[]=[];const add=(title:string,track:Recommendation['track'],personIds:string[],nextStep:string,rationale:string,actionIntent:Recommendation['actionIntent']='none',effortMinutes=15)=>rs.push({id:'choice-'+rs.length,title,track,personIds,kind:'self_directed',catalogId:null,sourceIds:[],nextStep,rationale,effortMinutes,effortLabel:'planning_estimate',requiresChecking:[],actionIntent});
 add('Shape your next work chapter','career',[lead.id],'Choose one work goal and update your introduction.',lead.goals.includes('Find work')?'You selected Find work.':'An optional work check-in; skip if it is not a priority.','draft_introduction',20);
 add('Refresh your portfolio or CV','career',[lead.id],'Pick three examples you would like to share.',lead.profession?'Based on your '+lead.profession+' background.':'A practical preparation step.','portfolio_checklist',25);
 const interest=social.interests[0]||'a shared interest';add('Find your '+interest.toLowerCase()+' people','community',[social.id],'Explore a public group, then prepare a short introduction.',social.interests.length?'You selected '+interest+'.':'Choose interests in Your people for closer matches.','draft_introduction',15);
 add('Try one social space','community',people.map(x=>x.id),'Browse the People tab and choose a comfortable first visit.','A public activity makes an easy starting point.');
 add(profile.people.some(x=>x.role==='child')?'Keep a family ritual':'Keep a familiar ritual','family',family,'Choose one familiar meal, walk or shared activity.','A routine for the people in your household.');
 add('Explore '+area.name,'family',family,'Compare this area with your work and school routes.',area.matches.length?'Matches your '+area.matches.join(' and ')+' choices.':'An area to explore; choose your preferred vibe for closer matches.', 'none',30);
 add('Find a first favourite meal','personal',people.map(x=>x.id),'Explore '+(p.cuisines[0]||'a cuisine you enjoy')+' spots in the Food tab.',p.cuisines.length?'Based on your food choices.':'Add food preferences to narrow the search.');
 add('Make room for '+(social.interests[1]||'yourself'),'personal',[social.id],'Set aside one small window for something you enjoy.',social.interests[1]?'You selected '+social.interests[1]+'.':'A little personal time, at your pace.');
 for(const src of sources.filter(x=>x.kind==='official').slice(0,1))rs.push({id:'choice-source-'+src.id,title:src.title.slice(0,100),track:src.track,personIds:family,kind:'catalog_resource',catalogId:src.id,sourceIds:[src.id],nextStep:'Check the original source before making arrangements.',rationale:'Official information for your household.',effortMinutes:15,effortLabel:'planning_estimate',requiresChecking:['Suitability and current requirements'],actionIntent:'none'});
 return validateBridge({id:'bridge-'+crypto.randomUUID(),profileId:profile.id,headline:'Your Abu Dhabi, taking shape.',summary:'A starting plan built from your choices.',tracks:tracks.map(id=>({id,goal:id,recommendationIds:rs.filter(r=>r.track===id).map(r=>r.id)})),recommendations:rs,featuredRecommendationId:rs[2].id,assumptions:['Suggested preparation steps; no bookings or messages are sent.']},profile,sources);
}
export function choiceDraft(r:Recommendation,profile:Profile,tone:'warm'|'concise',context:string):Draft{const person=profile.people.find(p=>r.personIds.includes(p.id)&&p.role!=='child')||profile.people[0];return {id:'draft-'+crypto.randomUUID(),recommendationId:r.id,intent:r.actionIntent==='portfolio_checklist'?'portfolio_checklist':'draft_introduction',title:r.actionIntent==='portfolio_checklist'?'Your preparation checklist':'A first hello',channel:'Copy and share with a contact you choose',recipientLabel:null,recipientAddress:null,subject:r.actionIntent==='portfolio_checklist'?null:'Hello from '+(person.name||'a new neighbour'),body:r.actionIntent==='portfolio_checklist'?'A few things to prepare before you reach out.':(tone==='warm'?'Hi there!':'Hello,')+' I’m '+(person.name||'a new neighbour')+(person.profession?', a '+person.profession:'')+'. I’m getting settled in Abu Dhabi and would love to connect with people who enjoy '+(person.interests.slice(0,3).join(', ')||'similar interests')+'. '+(context.trim()?context.trim()+' ':'')+'Do you have a public gathering or beginner-friendly activity you would recommend? Thank you!',checklist:r.actionIntent==='portfolio_checklist'?['Pick three relevant examples','Check that links open correctly','Write a short introduction','Choose who you want to contact']:['Choose the recipient','Review your details','Copy when ready'],sourceIds:r.sourceIds,reviewNotes:['Template built from your choices. Edit before sharing.'],executionStatus:'draft_only'};}

export function choiceWeek(b:Bridge):Week {return validateWeek({id:'week-'+crypto.randomUUID(),bridgeId:b.id,startDate:null,timezone:'Asia/Dubai',tasks:b.recommendations.map((r,i)=>({id:'task-'+crypto.randomUUID(),dayIndex:i<7?i+1:i-6,recommendationId:r.id,title:r.title,personIds:r.personIds,track:r.track,effortMinutes:r.effortMinutes,timeWindow:'flexible',rationale:r.rationale,requiresChecking:r.requiresChecking})),assumptions:['Suggested preparation sequence, not booked appointments.']},b);}
