import {evidenceSchema,type Evidence,type Source} from './contracts';
const API='https://api.smartrecruiters.com/v1/companies/EtihadAirways5/postings?city=Abu%20Dhabi&limit=100';
const ADEK='https://www.adek.gov.ae/Education-System';
const endpoints=new Set([API,ADEK]);
export function allowedFetch(url:string){if(!endpoints.has(url))throw Error('Destination is not allowlisted');return url;}
export async function boundedFetch(url:string,signal:AbortSignal):Promise<string>{
 allowedFetch(url);const res=await fetch(url,{signal,redirect:'manual',headers:{Accept:url===API?'application/json':'text/html'}});if(!res.ok)throw Error('Source HTTP '+res.status);const len=Number(res.headers.get('content-length')||0);if(len>750000)throw Error('Source too large');const reader=res.body?.getReader();if(!reader)throw Error('Empty source');let bytes=0;const decoder=new TextDecoder();let text='';while(true){const part=await reader.read();if(part.done)break;bytes+=part.value.byteLength;if(bytes>750000){await reader.cancel();throw Error('Source too large');}text+=decoder.decode(part.value,{stream:true});}return text+decoder.decode();
}
// Public metadata only. No narratives, profiles, raw pages or model content are cached.
const cache=new Map<string,{records:Source[];at:number}>();
const inFlight=new Map<string,Promise<{records:Source[];health:Evidence['health'][number]}>>();
export const checkedResources:Source[]=[{id:'cultural-foundation',title:'Cultural Foundation visitor resource',url:'https://culturalfoundation.ae/en/plan-your-visit',publisher:'Cultural Foundation',checkedAt:'2026-10-02T06:44:05.000Z',verifiedClaims:['Official visitor page links to exhibitions, programmes and the Children’s Library.'],verification:'checked',status:'checked',track:'personal',kind:'resource',description:'A visitor resource to explore and check directly. No programme schedule is reproduced.',location:'Abu Dhabi'}];
interface Posting {id?:unknown;name?:unknown;company?:{name?:unknown};location?:{city?:unknown;country?:unknown};}
export function normalizeJobs(raw:unknown,at:string):Source[]{if(!raw||typeof raw!=='object'||!('content' in raw)||!Array.isArray(raw.content))throw Error('Invalid job feed');return raw.content.filter((p:Posting)=>typeof p.name==='string'&&/design|creative|graphic|brand/i.test(p.name)&&typeof p.id==='string'&&/^\d+$/.test(p.id)&&typeof p.location?.city==='string'&&/^abu\s*dhabi$/i.test(p.location.city)&&p.location.country?.toString().toLowerCase()==='ae').slice(0,5).map((p:Posting)=>({id:'etihad-'+p.id,title:String(p.name).slice(0,150),url:'https://jobs.smartrecruiters.com/EtihadAirways5/'+p.id,publisher:typeof p.company?.name==='string'?p.company.name.slice(0,100):'Etihad Airways',checkedAt:at,verifiedClaims:['Provider lists this role in Abu Dhabi, United Arab Emirates.'],verification:'checked' as const,status:'live' as const,track:'career' as const,kind:'job' as const,description:'Provider-listed role. Review the original requirements and current availability. This is a discovery lead, not a verified skills or eligibility match.',location:'Abu Dhabi, UAE'}));}
async function retrieve(name:string,url:string,ttl:number,parse:(body:string,at:string)=>Source[]):Promise<{records:Source[];health:Evidence['health'][number]}>{
 const existing=cache.get(name);if(existing&&Date.now()-existing.at<ttl)return {records:existing.records.map(r=>({...r,status:'cached'})),health:{name,status:'cached',message:'Using the last successful public-data fetch.'}};
 const running=inFlight.get(name);if(running)return running;
 const request=(async()=>{try{const body=await boundedFetch(url,AbortSignal.timeout(7500));const at=new Date().toISOString();const records=parse(body,at);cache.set(name,{records,at:Date.now()});return {records,health:{name,status:'live' as const,message:records.length?'Retrieved from the original source.':'No relevant Abu Dhabi design records returned.'}};}catch{return existing?{records:existing.records.map(r=>({...r,status:'cached' as const})),health:{name,status:'cached' as const,message:'Source unavailable; showing the last successful fetch. Recheck directly.'}}:{records:[],health:{name,status:'unavailable' as const,message:'Could not retrieve this source. Use preparation tasks or retry.'}};}finally{inFlight.delete(name);}})();inFlight.set(name,request);return request;
}
export async function getEvidence():Promise<Evidence>{
 const [jobs,official]=await Promise.all([retrieve('Etihad / SmartRecruiters',API,15*60000,(body,at)=>normalizeJobs(JSON.parse(body),at)),retrieve('ADEK official education information',ADEK,24*60*60000,(body,at)=>{if(!/<title>\s*Education System\s*<\/title>/i.test(body)||!body.includes('Nurseries')||!body.includes('Private Schools'))throw Error('Official page inaccessible');return [{id:'adek-education',title:'ADEK: Education System',url:ADEK,publisher:'Abu Dhabi Department of Education and Knowledge',checkedAt:at,verifiedClaims:['ADEK’s education page links to nursery and private-school information for Abu Dhabi.'],verification:'checked',status:'live',track:'family',kind:'official',description:'ADEK provides official links to nursery and private-school information in Abu Dhabi. Review options for Lina and check age suitability and admissions directly; this is not an eligibility decision.',location:'Abu Dhabi'}];})]);
 const records=[...jobs.records,...official.records,...checkedResources];const statuses=new Set(records.map(r=>r.status));return evidenceSchema.parse({records,health:[jobs.health,official.health,{name:'Cultural Foundation',status:'checked',message:'Manually checked reference link; not fetched live by BRIDGE.'}],evidenceMode:statuses.size===1&&statuses.has('live')?'live':statuses.size===1&&statuses.has('cached')?'cached':'mixed',retrievedAt:new Date().toISOString()});
}
